"""Drawings for parts that have their own .FCStd geometry (designed parts,
or purchased parts modelled directly) - run under freecadcmd."""
import os
import zipfile

import pytest

pytest.importorskip("FreeCAD")
import FreeCAD as App
import Part

from gwtcad import methods, session, supplier_models as sm
from gwtcad import partnumbers as pn


@pytest.fixture(autouse=True)
def no_upload(monkeypatch):
    monkeypatch.setattr(sm._storage, "upload_file", lambda *a, **k: None)


@pytest.fixture
def bracket(company_config, cad_repo):
    r = pn.pn_reserve("CM", "J", 1, "bracket", "Test Bracket")
    path = os.path.join(str(cad_repo), r["repoRelpath"])
    os.makedirs(os.path.dirname(path), exist_ok=True)
    d = App.newDocument("bracket")
    o = d.addObject("Part::Feature", "Body")
    o.Shape = Part.makeBox(40, 20, 5).fuse(Part.makeCylinder(4, 15, App.Vector(10, 10, 0)))
    d.recompute()
    d.saveAs(path)
    App.closeDocument(d.Name)
    yield path
    for doc in list(App.listDocuments().values()):
        App.closeDocument(doc.Name)


def _pages(path):
    return zipfile.ZipFile(path).read("Document.xml").count(b'type="TechDraw::DrawPage"')


def test_a_designed_part_gets_a_drawing_from_its_own_geometry(bracket):
    assert not sm._file_has_drawing(bracket)
    r = sm.generate_part_drawing("CMJ0010")
    assert r.get("generated"), r
    assert sm._file_has_drawing(bracket)
    d = App.openDocument(bracket)
    page = next(o for o in d.Objects if o.TypeId == "TechDraw::DrawPage")
    info = sm._auto_drawing_info(page)
    assert info["pn"] == "CMJ0010" and info["notes"] == []  # no supplier, no equivalence note
    assert d.GwtPartNumber == "CMJ0010"


def test_the_startup_scan_draws_only_parts_that_lack_one(bracket):
    out = sm.generate_missing_drawings()
    assert [x["pn"] for x in out] == ["CMJ0010"] and out[0].get("generated")
    assert sm.generate_missing_drawings() == []  # already drawn: nothing to do
    assert _pages(bracket) == 1


def test_promoting_the_open_part_draws_it_in_place(bracket):
    methods.document_open(bracket)
    r = sm.ensure_drawing_or_block("CMJ0010")
    assert r["ok"] and r.get("autoGenerated"), r
    d = session.doc(create=False)
    assert d is not None and d.FileName == bracket  # still the open part
    assert any(o.TypeId == "TechDraw::DrawPage" for o in d.Objects)
    assert _pages(bracket) == 1
