"""Drawings for parts that have their own .FCStd geometry (designed parts,
or purchased parts modelled directly) - run under freecadcmd."""
import os
import zipfile

import pytest

pytest.importorskip("FreeCAD")
import FreeCAD as App
import Part

from gwtcad import methods, session, supplier_models as sm
from gwtcad import partnumbers as pn


@pytest.fixture(autouse=True)
def no_upload(monkeypatch):
    monkeypatch.setattr(sm._storage, "upload_file", lambda *a, **k: None)


@pytest.fixture
def bracket(company_config, cad_repo):
    r = pn.pn_reserve("CM", "J", 1, "bracket", "Test Bracket")
    path = os.path.join(str(cad_repo), r["repoRelpath"])
    os.makedirs(os.path.dirname(path), exist_ok=True)
    d = App.newDocument("bracket")
    o = d.addObject("Part::Feature", "Body")
    o.Shape = Part.makeBox(40, 20, 5).fuse(Part.makeCylinder(4, 15, App.Vector(10, 10, 0)))
    d.recompute()
    d.saveAs(path)
    App.closeDocument(d.Name)
    yield path
    for doc in list(App.listDocuments().values()):
        App.closeDocument(doc.Name)


def _pages(path):
    return zipfile.ZipFile(path).read("Document.xml").count(b'type="TechDraw::DrawPage"')


def test_a_designed_part_gets_a_drawing_from_its_own_geometry(bracket):
    assert not sm._file_has_drawing(bracket)
    r = sm.generate_part_drawing("CMJ0010")
    assert r.get("generated"), r
    assert sm._file_has_drawing(bracket)
    d = App.openDocument(bracket)
    page = next(o for o in d.Objects if o.TypeId == "TechDraw::DrawPage")
    info = sm._auto_drawing_info(page)
    assert info["pn"] == "CMJ0010" and info["notes"] == []  # no supplier, no equivalence note
    assert d.GwtPartNumber == "CMJ0010"


def test_a_part_drawing_is_published_to_the_portal(bracket, monkeypatch):
    # regression: drawings made from a part's own .FCStd were only saved
    # into the file, so 40 parts had a drawing the portal never showed
    uploads = []
    monkeypatch.setattr(sm._storage, "upload_file", lambda path, dest, ctype: uploads.append((dest, os.path.getsize(path))))
    assert sm.generate_part_drawing("CMJ0010").get("generated")
    assert [u[0] for u in uploads] == ["cad-exports/CMJ0010/CMJ0010.pdf"] and uploads[0][1] > 0


def test_a_failed_upload_still_keeps_the_drawing(bracket, monkeypatch):
    def offline(*a, **k):
        raise RuntimeError("no Firebase key")
    monkeypatch.setattr(sm._storage, "upload_file", offline)
    assert sm.generate_part_drawing("CMJ0010").get("generated")
    assert _pages(bracket) == 1


def test_the_startup_scan_draws_only_parts_that_lack_one(bracket):
    out = sm.generate_missing_drawings()
    assert [x["pn"] for x in out] == ["CMJ0010"] and out[0].get("generated")
    assert sm.generate_missing_drawings() == []  # already drawn: nothing to do
    assert _pages(bracket) == 1


def test_promoting_the_open_part_draws_it_in_place(bracket):
    methods.document_open(bracket)
    r = sm.ensure_drawing_or_block("CMJ0010")
    assert r["ok"] and r.get("autoGenerated"), r
    d = session.doc(create=False)
    assert d is not None and d.FileName == bracket  # still the open part
    assert any(o.TypeId == "TechDraw::DrawPage" for o in d.Objects)
    assert _pages(bracket) == 1


def test_the_startup_scan_draws_in_a_separate_process(bracket, monkeypatch, tmp_path):
    # the engine thread must never wait on hidden-line removal: the scan is
    # a detached freecadcmd that finishes on its own
    import time
    monkeypatch.setenv("GWTCAD_CONFIG_DIR", str(tmp_path / "cfg"))
    os.makedirs(str(tmp_path / "cfg"))
    import shutil
    shutil.copy(pn._CONFIG_PATH, str(tmp_path / "cfg" / "company.json"))
    t = time.time()
    pid = sm.start_missing_drawings_job()
    assert pid and time.time() - t < 2
    for _ in range(600):
        try:
            os.kill(pid, 0)
        except ProcessLookupError:
            break
        try:
            os.waitpid(pid, os.WNOHANG)
        except ChildProcessError:
            pass
        time.sleep(0.25)
    assert sm._file_has_drawing(bracket)


def test_saving_a_printed_part_records_its_volume_for_pricing(company_config, cad_repo):
    # the portal prices 3D-printed (J) parts as filament from this volume
    r = pn.pn_reserve("CM", "J", 2, "cover", "Test Cover")
    path = os.path.join(str(cad_repo), r["repoRelpath"])
    os.makedirs(os.path.dirname(path), exist_ok=True)
    d = App.newDocument("cover")
    o = d.addObject("Part::Feature", "Body")
    o.Shape = Part.makeBox(40, 20, 5)  # 4.0 cm3
    d.recompute()
    session.set_part_number({"pn": r["pn"], "name": "cover", "description": "Test Cover"})
    try:
        methods._record_print_volume(d)
        row = pn._row_for_pn(pn._read_registry(pn._load_config()), r["pn"])
        assert row["print_volume_cm3"] == "4.0"
        # an unchanged part adds no registry history
        assert pn.pn_record_print_volume(r["pn"], 4.0) is False
    finally:
        App.closeDocument(d.Name)


def test_non_printed_parts_record_no_volume(company_config, cad_repo):
    r = pn.pn_reserve("CM", "D", 1, "bracket", "Test Bracket")
    d = App.newDocument("bracket2")
    o = d.addObject("Part::Feature", "Body")
    o.Shape = Part.makeBox(10, 10, 10)
    d.recompute()
    session.set_part_number({"pn": r["pn"], "name": "bracket", "description": "Test Bracket"})
    try:
        methods._record_print_volume(d)
        row = pn._row_for_pn(pn._read_registry(pn._load_config()), r["pn"])
        assert not row.get("print_volume_cm3")
    finally:
        App.closeDocument(d.Name)
